//! JVMTI auto bindings
//! - JVMTI bindings generated by bindgen at compile time for dependents.
//! How to use:
//! - Add ``jvmti-autobindings`` to your dependencies.
//! - Make sure JAVA_HOME is set to your java home directory.
//! - Compile!
//!
//! Recommendations:
//! - When compiling your crate containing this as a dependent, keep the outputted bindgen so other people attempting to compile your crate doesn't get a version mismatch.
//! - For docs on how to use JVMTI go to ``https://docs.oracle.com/en/java/javase/{INSERT_YOUR_JAVA_VERSION}/docs/specs/jvmti.html``

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
include!(concat!(env!("OUT_DIR"), "/jvmti_bindings.rs"));